
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MisskonTag` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MisskonTag
 * 
 */
export type MisskonTagModel = runtime.Types.Result.DefaultSelection<Prisma.$MisskonTagPayload>

export type AggregateMisskonTag = {
  _count: MisskonTagCountAggregateOutputType | null
  _avg: MisskonTagAvgAggregateOutputType | null
  _sum: MisskonTagSumAggregateOutputType | null
  _min: MisskonTagMinAggregateOutputType | null
  _max: MisskonTagMaxAggregateOutputType | null
}

export type MisskonTagAvgAggregateOutputType = {
  id: number | null
  like: number | null
}

export type MisskonTagSumAggregateOutputType = {
  id: number | null
  like: number | null
}

export type MisskonTagMinAggregateOutputType = {
  id: number | null
  name: string | null
  url: string | null
  like: number | null
}

export type MisskonTagMaxAggregateOutputType = {
  id: number | null
  name: string | null
  url: string | null
  like: number | null
}

export type MisskonTagCountAggregateOutputType = {
  id: number
  name: number
  url: number
  like: number
  _all: number
}


export type MisskonTagAvgAggregateInputType = {
  id?: true
  like?: true
}

export type MisskonTagSumAggregateInputType = {
  id?: true
  like?: true
}

export type MisskonTagMinAggregateInputType = {
  id?: true
  name?: true
  url?: true
  like?: true
}

export type MisskonTagMaxAggregateInputType = {
  id?: true
  name?: true
  url?: true
  like?: true
}

export type MisskonTagCountAggregateInputType = {
  id?: true
  name?: true
  url?: true
  like?: true
  _all?: true
}

export type MisskonTagAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MisskonTag to aggregate.
   */
  where?: Prisma.MisskonTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MisskonTags to fetch.
   */
  orderBy?: Prisma.MisskonTagOrderByWithRelationInput | Prisma.MisskonTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MisskonTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MisskonTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MisskonTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MisskonTags
  **/
  _count?: true | MisskonTagCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MisskonTagAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MisskonTagSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MisskonTagMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MisskonTagMaxAggregateInputType
}

export type GetMisskonTagAggregateType<T extends MisskonTagAggregateArgs> = {
      [P in keyof T & keyof AggregateMisskonTag]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMisskonTag[P]>
    : Prisma.GetScalarType<T[P], AggregateMisskonTag[P]>
}




export type MisskonTagGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MisskonTagWhereInput
  orderBy?: Prisma.MisskonTagOrderByWithAggregationInput | Prisma.MisskonTagOrderByWithAggregationInput[]
  by: Prisma.MisskonTagScalarFieldEnum[] | Prisma.MisskonTagScalarFieldEnum
  having?: Prisma.MisskonTagScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MisskonTagCountAggregateInputType | true
  _avg?: MisskonTagAvgAggregateInputType
  _sum?: MisskonTagSumAggregateInputType
  _min?: MisskonTagMinAggregateInputType
  _max?: MisskonTagMaxAggregateInputType
}

export type MisskonTagGroupByOutputType = {
  id: number
  name: string
  url: string
  like: number
  _count: MisskonTagCountAggregateOutputType | null
  _avg: MisskonTagAvgAggregateOutputType | null
  _sum: MisskonTagSumAggregateOutputType | null
  _min: MisskonTagMinAggregateOutputType | null
  _max: MisskonTagMaxAggregateOutputType | null
}

export type GetMisskonTagGroupByPayload<T extends MisskonTagGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MisskonTagGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MisskonTagGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MisskonTagGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MisskonTagGroupByOutputType[P]>
      }
    >
  >



export type MisskonTagWhereInput = {
  AND?: Prisma.MisskonTagWhereInput | Prisma.MisskonTagWhereInput[]
  OR?: Prisma.MisskonTagWhereInput[]
  NOT?: Prisma.MisskonTagWhereInput | Prisma.MisskonTagWhereInput[]
  id?: Prisma.IntFilter<"MisskonTag"> | number
  name?: Prisma.StringFilter<"MisskonTag"> | string
  url?: Prisma.StringFilter<"MisskonTag"> | string
  like?: Prisma.IntFilter<"MisskonTag"> | number
  resources?: Prisma.MisskonListRelationFilter
}

export type MisskonTagOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  like?: Prisma.SortOrder
  resources?: Prisma.MisskonOrderByRelationAggregateInput
}

export type MisskonTagWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  name?: string
  url?: string
  AND?: Prisma.MisskonTagWhereInput | Prisma.MisskonTagWhereInput[]
  OR?: Prisma.MisskonTagWhereInput[]
  NOT?: Prisma.MisskonTagWhereInput | Prisma.MisskonTagWhereInput[]
  like?: Prisma.IntFilter<"MisskonTag"> | number
  resources?: Prisma.MisskonListRelationFilter
}, "id" | "name" | "url">

export type MisskonTagOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  like?: Prisma.SortOrder
  _count?: Prisma.MisskonTagCountOrderByAggregateInput
  _avg?: Prisma.MisskonTagAvgOrderByAggregateInput
  _max?: Prisma.MisskonTagMaxOrderByAggregateInput
  _min?: Prisma.MisskonTagMinOrderByAggregateInput
  _sum?: Prisma.MisskonTagSumOrderByAggregateInput
}

export type MisskonTagScalarWhereWithAggregatesInput = {
  AND?: Prisma.MisskonTagScalarWhereWithAggregatesInput | Prisma.MisskonTagScalarWhereWithAggregatesInput[]
  OR?: Prisma.MisskonTagScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MisskonTagScalarWhereWithAggregatesInput | Prisma.MisskonTagScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"MisskonTag"> | number
  name?: Prisma.StringWithAggregatesFilter<"MisskonTag"> | string
  url?: Prisma.StringWithAggregatesFilter<"MisskonTag"> | string
  like?: Prisma.IntWithAggregatesFilter<"MisskonTag"> | number
}

export type MisskonTagCreateInput = {
  name: string
  url: string
  like?: number
  resources?: Prisma.MisskonCreateNestedManyWithoutTagsInput
}

export type MisskonTagUncheckedCreateInput = {
  id?: number
  name: string
  url: string
  like?: number
  resources?: Prisma.MisskonUncheckedCreateNestedManyWithoutTagsInput
}

export type MisskonTagUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  like?: Prisma.IntFieldUpdateOperationsInput | number
  resources?: Prisma.MisskonUpdateManyWithoutTagsNestedInput
}

export type MisskonTagUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  like?: Prisma.IntFieldUpdateOperationsInput | number
  resources?: Prisma.MisskonUncheckedUpdateManyWithoutTagsNestedInput
}

export type MisskonTagCreateManyInput = {
  id?: number
  name: string
  url: string
  like?: number
}

export type MisskonTagUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  like?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MisskonTagUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  like?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MisskonTagListRelationFilter = {
  every?: Prisma.MisskonTagWhereInput
  some?: Prisma.MisskonTagWhereInput
  none?: Prisma.MisskonTagWhereInput
}

export type MisskonTagOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MisskonTagCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  like?: Prisma.SortOrder
}

export type MisskonTagAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  like?: Prisma.SortOrder
}

export type MisskonTagMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  like?: Prisma.SortOrder
}

export type MisskonTagMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  like?: Prisma.SortOrder
}

export type MisskonTagSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  like?: Prisma.SortOrder
}

export type MisskonTagCreateNestedManyWithoutResourcesInput = {
  create?: Prisma.XOR<Prisma.MisskonTagCreateWithoutResourcesInput, Prisma.MisskonTagUncheckedCreateWithoutResourcesInput> | Prisma.MisskonTagCreateWithoutResourcesInput[] | Prisma.MisskonTagUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.MisskonTagCreateOrConnectWithoutResourcesInput | Prisma.MisskonTagCreateOrConnectWithoutResourcesInput[]
  connect?: Prisma.MisskonTagWhereUniqueInput | Prisma.MisskonTagWhereUniqueInput[]
}

export type MisskonTagUncheckedCreateNestedManyWithoutResourcesInput = {
  create?: Prisma.XOR<Prisma.MisskonTagCreateWithoutResourcesInput, Prisma.MisskonTagUncheckedCreateWithoutResourcesInput> | Prisma.MisskonTagCreateWithoutResourcesInput[] | Prisma.MisskonTagUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.MisskonTagCreateOrConnectWithoutResourcesInput | Prisma.MisskonTagCreateOrConnectWithoutResourcesInput[]
  connect?: Prisma.MisskonTagWhereUniqueInput | Prisma.MisskonTagWhereUniqueInput[]
}

export type MisskonTagUpdateManyWithoutResourcesNestedInput = {
  create?: Prisma.XOR<Prisma.MisskonTagCreateWithoutResourcesInput, Prisma.MisskonTagUncheckedCreateWithoutResourcesInput> | Prisma.MisskonTagCreateWithoutResourcesInput[] | Prisma.MisskonTagUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.MisskonTagCreateOrConnectWithoutResourcesInput | Prisma.MisskonTagCreateOrConnectWithoutResourcesInput[]
  upsert?: Prisma.MisskonTagUpsertWithWhereUniqueWithoutResourcesInput | Prisma.MisskonTagUpsertWithWhereUniqueWithoutResourcesInput[]
  set?: Prisma.MisskonTagWhereUniqueInput | Prisma.MisskonTagWhereUniqueInput[]
  disconnect?: Prisma.MisskonTagWhereUniqueInput | Prisma.MisskonTagWhereUniqueInput[]
  delete?: Prisma.MisskonTagWhereUniqueInput | Prisma.MisskonTagWhereUniqueInput[]
  connect?: Prisma.MisskonTagWhereUniqueInput | Prisma.MisskonTagWhereUniqueInput[]
  update?: Prisma.MisskonTagUpdateWithWhereUniqueWithoutResourcesInput | Prisma.MisskonTagUpdateWithWhereUniqueWithoutResourcesInput[]
  updateMany?: Prisma.MisskonTagUpdateManyWithWhereWithoutResourcesInput | Prisma.MisskonTagUpdateManyWithWhereWithoutResourcesInput[]
  deleteMany?: Prisma.MisskonTagScalarWhereInput | Prisma.MisskonTagScalarWhereInput[]
}

export type MisskonTagUncheckedUpdateManyWithoutResourcesNestedInput = {
  create?: Prisma.XOR<Prisma.MisskonTagCreateWithoutResourcesInput, Prisma.MisskonTagUncheckedCreateWithoutResourcesInput> | Prisma.MisskonTagCreateWithoutResourcesInput[] | Prisma.MisskonTagUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.MisskonTagCreateOrConnectWithoutResourcesInput | Prisma.MisskonTagCreateOrConnectWithoutResourcesInput[]
  upsert?: Prisma.MisskonTagUpsertWithWhereUniqueWithoutResourcesInput | Prisma.MisskonTagUpsertWithWhereUniqueWithoutResourcesInput[]
  set?: Prisma.MisskonTagWhereUniqueInput | Prisma.MisskonTagWhereUniqueInput[]
  disconnect?: Prisma.MisskonTagWhereUniqueInput | Prisma.MisskonTagWhereUniqueInput[]
  delete?: Prisma.MisskonTagWhereUniqueInput | Prisma.MisskonTagWhereUniqueInput[]
  connect?: Prisma.MisskonTagWhereUniqueInput | Prisma.MisskonTagWhereUniqueInput[]
  update?: Prisma.MisskonTagUpdateWithWhereUniqueWithoutResourcesInput | Prisma.MisskonTagUpdateWithWhereUniqueWithoutResourcesInput[]
  updateMany?: Prisma.MisskonTagUpdateManyWithWhereWithoutResourcesInput | Prisma.MisskonTagUpdateManyWithWhereWithoutResourcesInput[]
  deleteMany?: Prisma.MisskonTagScalarWhereInput | Prisma.MisskonTagScalarWhereInput[]
}

export type MisskonTagCreateWithoutResourcesInput = {
  name: string
  url: string
  like?: number
}

export type MisskonTagUncheckedCreateWithoutResourcesInput = {
  id?: number
  name: string
  url: string
  like?: number
}

export type MisskonTagCreateOrConnectWithoutResourcesInput = {
  where: Prisma.MisskonTagWhereUniqueInput
  create: Prisma.XOR<Prisma.MisskonTagCreateWithoutResourcesInput, Prisma.MisskonTagUncheckedCreateWithoutResourcesInput>
}

export type MisskonTagUpsertWithWhereUniqueWithoutResourcesInput = {
  where: Prisma.MisskonTagWhereUniqueInput
  update: Prisma.XOR<Prisma.MisskonTagUpdateWithoutResourcesInput, Prisma.MisskonTagUncheckedUpdateWithoutResourcesInput>
  create: Prisma.XOR<Prisma.MisskonTagCreateWithoutResourcesInput, Prisma.MisskonTagUncheckedCreateWithoutResourcesInput>
}

export type MisskonTagUpdateWithWhereUniqueWithoutResourcesInput = {
  where: Prisma.MisskonTagWhereUniqueInput
  data: Prisma.XOR<Prisma.MisskonTagUpdateWithoutResourcesInput, Prisma.MisskonTagUncheckedUpdateWithoutResourcesInput>
}

export type MisskonTagUpdateManyWithWhereWithoutResourcesInput = {
  where: Prisma.MisskonTagScalarWhereInput
  data: Prisma.XOR<Prisma.MisskonTagUpdateManyMutationInput, Prisma.MisskonTagUncheckedUpdateManyWithoutResourcesInput>
}

export type MisskonTagScalarWhereInput = {
  AND?: Prisma.MisskonTagScalarWhereInput | Prisma.MisskonTagScalarWhereInput[]
  OR?: Prisma.MisskonTagScalarWhereInput[]
  NOT?: Prisma.MisskonTagScalarWhereInput | Prisma.MisskonTagScalarWhereInput[]
  id?: Prisma.IntFilter<"MisskonTag"> | number
  name?: Prisma.StringFilter<"MisskonTag"> | string
  url?: Prisma.StringFilter<"MisskonTag"> | string
  like?: Prisma.IntFilter<"MisskonTag"> | number
}

export type MisskonTagUpdateWithoutResourcesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  like?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MisskonTagUncheckedUpdateWithoutResourcesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  like?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MisskonTagUncheckedUpdateManyWithoutResourcesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  like?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type MisskonTagCountOutputType
 */

export type MisskonTagCountOutputType = {
  resources: number
}

export type MisskonTagCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resources?: boolean | MisskonTagCountOutputTypeCountResourcesArgs
}

/**
 * MisskonTagCountOutputType without action
 */
export type MisskonTagCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonTagCountOutputType
   */
  select?: Prisma.MisskonTagCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MisskonTagCountOutputType without action
 */
export type MisskonTagCountOutputTypeCountResourcesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MisskonWhereInput
}


export type MisskonTagSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  url?: boolean
  like?: boolean
  resources?: boolean | Prisma.MisskonTag$resourcesArgs<ExtArgs>
  _count?: boolean | Prisma.MisskonTagCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["misskonTag"]>

export type MisskonTagSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  url?: boolean
  like?: boolean
}, ExtArgs["result"]["misskonTag"]>

export type MisskonTagSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  url?: boolean
  like?: boolean
}, ExtArgs["result"]["misskonTag"]>

export type MisskonTagSelectScalar = {
  id?: boolean
  name?: boolean
  url?: boolean
  like?: boolean
}

export type MisskonTagOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "url" | "like", ExtArgs["result"]["misskonTag"]>
export type MisskonTagInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resources?: boolean | Prisma.MisskonTag$resourcesArgs<ExtArgs>
  _count?: boolean | Prisma.MisskonTagCountOutputTypeDefaultArgs<ExtArgs>
}
export type MisskonTagIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type MisskonTagIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $MisskonTagPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MisskonTag"
  objects: {
    resources: Prisma.$MisskonPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    url: string
    like: number
  }, ExtArgs["result"]["misskonTag"]>
  composites: {}
}

export type MisskonTagGetPayload<S extends boolean | null | undefined | MisskonTagDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MisskonTagPayload, S>

export type MisskonTagCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MisskonTagFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: MisskonTagCountAggregateInputType | true
  }

export interface MisskonTagDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MisskonTag'], meta: { name: 'MisskonTag' } }
  /**
   * Find zero or one MisskonTag that matches the filter.
   * @param {MisskonTagFindUniqueArgs} args - Arguments to find a MisskonTag
   * @example
   * // Get one MisskonTag
   * const misskonTag = await prisma.misskonTag.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MisskonTagFindUniqueArgs>(args: Prisma.SelectSubset<T, MisskonTagFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MisskonTagClient<runtime.Types.Result.GetResult<Prisma.$MisskonTagPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MisskonTag that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MisskonTagFindUniqueOrThrowArgs} args - Arguments to find a MisskonTag
   * @example
   * // Get one MisskonTag
   * const misskonTag = await prisma.misskonTag.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MisskonTagFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MisskonTagFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MisskonTagClient<runtime.Types.Result.GetResult<Prisma.$MisskonTagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MisskonTag that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MisskonTagFindFirstArgs} args - Arguments to find a MisskonTag
   * @example
   * // Get one MisskonTag
   * const misskonTag = await prisma.misskonTag.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MisskonTagFindFirstArgs>(args?: Prisma.SelectSubset<T, MisskonTagFindFirstArgs<ExtArgs>>): Prisma.Prisma__MisskonTagClient<runtime.Types.Result.GetResult<Prisma.$MisskonTagPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MisskonTag that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MisskonTagFindFirstOrThrowArgs} args - Arguments to find a MisskonTag
   * @example
   * // Get one MisskonTag
   * const misskonTag = await prisma.misskonTag.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MisskonTagFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MisskonTagFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MisskonTagClient<runtime.Types.Result.GetResult<Prisma.$MisskonTagPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MisskonTags that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MisskonTagFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MisskonTags
   * const misskonTags = await prisma.misskonTag.findMany()
   * 
   * // Get first 10 MisskonTags
   * const misskonTags = await prisma.misskonTag.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const misskonTagWithIdOnly = await prisma.misskonTag.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MisskonTagFindManyArgs>(args?: Prisma.SelectSubset<T, MisskonTagFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MisskonTagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MisskonTag.
   * @param {MisskonTagCreateArgs} args - Arguments to create a MisskonTag.
   * @example
   * // Create one MisskonTag
   * const MisskonTag = await prisma.misskonTag.create({
   *   data: {
   *     // ... data to create a MisskonTag
   *   }
   * })
   * 
   */
  create<T extends MisskonTagCreateArgs>(args: Prisma.SelectSubset<T, MisskonTagCreateArgs<ExtArgs>>): Prisma.Prisma__MisskonTagClient<runtime.Types.Result.GetResult<Prisma.$MisskonTagPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MisskonTags.
   * @param {MisskonTagCreateManyArgs} args - Arguments to create many MisskonTags.
   * @example
   * // Create many MisskonTags
   * const misskonTag = await prisma.misskonTag.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MisskonTagCreateManyArgs>(args?: Prisma.SelectSubset<T, MisskonTagCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MisskonTags and returns the data saved in the database.
   * @param {MisskonTagCreateManyAndReturnArgs} args - Arguments to create many MisskonTags.
   * @example
   * // Create many MisskonTags
   * const misskonTag = await prisma.misskonTag.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MisskonTags and only return the `id`
   * const misskonTagWithIdOnly = await prisma.misskonTag.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MisskonTagCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MisskonTagCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MisskonTagPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MisskonTag.
   * @param {MisskonTagDeleteArgs} args - Arguments to delete one MisskonTag.
   * @example
   * // Delete one MisskonTag
   * const MisskonTag = await prisma.misskonTag.delete({
   *   where: {
   *     // ... filter to delete one MisskonTag
   *   }
   * })
   * 
   */
  delete<T extends MisskonTagDeleteArgs>(args: Prisma.SelectSubset<T, MisskonTagDeleteArgs<ExtArgs>>): Prisma.Prisma__MisskonTagClient<runtime.Types.Result.GetResult<Prisma.$MisskonTagPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MisskonTag.
   * @param {MisskonTagUpdateArgs} args - Arguments to update one MisskonTag.
   * @example
   * // Update one MisskonTag
   * const misskonTag = await prisma.misskonTag.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MisskonTagUpdateArgs>(args: Prisma.SelectSubset<T, MisskonTagUpdateArgs<ExtArgs>>): Prisma.Prisma__MisskonTagClient<runtime.Types.Result.GetResult<Prisma.$MisskonTagPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MisskonTags.
   * @param {MisskonTagDeleteManyArgs} args - Arguments to filter MisskonTags to delete.
   * @example
   * // Delete a few MisskonTags
   * const { count } = await prisma.misskonTag.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MisskonTagDeleteManyArgs>(args?: Prisma.SelectSubset<T, MisskonTagDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MisskonTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MisskonTagUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MisskonTags
   * const misskonTag = await prisma.misskonTag.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MisskonTagUpdateManyArgs>(args: Prisma.SelectSubset<T, MisskonTagUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MisskonTags and returns the data updated in the database.
   * @param {MisskonTagUpdateManyAndReturnArgs} args - Arguments to update many MisskonTags.
   * @example
   * // Update many MisskonTags
   * const misskonTag = await prisma.misskonTag.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MisskonTags and only return the `id`
   * const misskonTagWithIdOnly = await prisma.misskonTag.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MisskonTagUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MisskonTagUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MisskonTagPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MisskonTag.
   * @param {MisskonTagUpsertArgs} args - Arguments to update or create a MisskonTag.
   * @example
   * // Update or create a MisskonTag
   * const misskonTag = await prisma.misskonTag.upsert({
   *   create: {
   *     // ... data to create a MisskonTag
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MisskonTag we want to update
   *   }
   * })
   */
  upsert<T extends MisskonTagUpsertArgs>(args: Prisma.SelectSubset<T, MisskonTagUpsertArgs<ExtArgs>>): Prisma.Prisma__MisskonTagClient<runtime.Types.Result.GetResult<Prisma.$MisskonTagPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MisskonTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MisskonTagCountArgs} args - Arguments to filter MisskonTags to count.
   * @example
   * // Count the number of MisskonTags
   * const count = await prisma.misskonTag.count({
   *   where: {
   *     // ... the filter for the MisskonTags we want to count
   *   }
   * })
  **/
  count<T extends MisskonTagCountArgs>(
    args?: Prisma.Subset<T, MisskonTagCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MisskonTagCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MisskonTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MisskonTagAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MisskonTagAggregateArgs>(args: Prisma.Subset<T, MisskonTagAggregateArgs>): Prisma.PrismaPromise<GetMisskonTagAggregateType<T>>

  /**
   * Group by MisskonTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MisskonTagGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MisskonTagGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MisskonTagGroupByArgs['orderBy'] }
      : { orderBy?: MisskonTagGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MisskonTagGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMisskonTagGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MisskonTag model
 */
readonly fields: MisskonTagFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MisskonTag.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MisskonTagClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  resources<T extends Prisma.MisskonTag$resourcesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MisskonTag$resourcesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MisskonPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MisskonTag model
 */
export interface MisskonTagFieldRefs {
  readonly id: Prisma.FieldRef<"MisskonTag", 'Int'>
  readonly name: Prisma.FieldRef<"MisskonTag", 'String'>
  readonly url: Prisma.FieldRef<"MisskonTag", 'String'>
  readonly like: Prisma.FieldRef<"MisskonTag", 'Int'>
}
    

// Custom InputTypes
/**
 * MisskonTag findUnique
 */
export type MisskonTagFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonTag
   */
  select?: Prisma.MisskonTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MisskonTag
   */
  omit?: Prisma.MisskonTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonTagInclude<ExtArgs> | null
  /**
   * Filter, which MisskonTag to fetch.
   */
  where: Prisma.MisskonTagWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * MisskonTag findUniqueOrThrow
 */
export type MisskonTagFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonTag
   */
  select?: Prisma.MisskonTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MisskonTag
   */
  omit?: Prisma.MisskonTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonTagInclude<ExtArgs> | null
  /**
   * Filter, which MisskonTag to fetch.
   */
  where: Prisma.MisskonTagWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * MisskonTag findFirst
 */
export type MisskonTagFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonTag
   */
  select?: Prisma.MisskonTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MisskonTag
   */
  omit?: Prisma.MisskonTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonTagInclude<ExtArgs> | null
  /**
   * Filter, which MisskonTag to fetch.
   */
  where?: Prisma.MisskonTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MisskonTags to fetch.
   */
  orderBy?: Prisma.MisskonTagOrderByWithRelationInput | Prisma.MisskonTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MisskonTags.
   */
  cursor?: Prisma.MisskonTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MisskonTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MisskonTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MisskonTags.
   */
  distinct?: Prisma.MisskonTagScalarFieldEnum | Prisma.MisskonTagScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * MisskonTag findFirstOrThrow
 */
export type MisskonTagFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonTag
   */
  select?: Prisma.MisskonTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MisskonTag
   */
  omit?: Prisma.MisskonTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonTagInclude<ExtArgs> | null
  /**
   * Filter, which MisskonTag to fetch.
   */
  where?: Prisma.MisskonTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MisskonTags to fetch.
   */
  orderBy?: Prisma.MisskonTagOrderByWithRelationInput | Prisma.MisskonTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MisskonTags.
   */
  cursor?: Prisma.MisskonTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MisskonTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MisskonTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MisskonTags.
   */
  distinct?: Prisma.MisskonTagScalarFieldEnum | Prisma.MisskonTagScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * MisskonTag findMany
 */
export type MisskonTagFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonTag
   */
  select?: Prisma.MisskonTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MisskonTag
   */
  omit?: Prisma.MisskonTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonTagInclude<ExtArgs> | null
  /**
   * Filter, which MisskonTags to fetch.
   */
  where?: Prisma.MisskonTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MisskonTags to fetch.
   */
  orderBy?: Prisma.MisskonTagOrderByWithRelationInput | Prisma.MisskonTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MisskonTags.
   */
  cursor?: Prisma.MisskonTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MisskonTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MisskonTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MisskonTags.
   */
  distinct?: Prisma.MisskonTagScalarFieldEnum | Prisma.MisskonTagScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * MisskonTag create
 */
export type MisskonTagCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonTag
   */
  select?: Prisma.MisskonTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MisskonTag
   */
  omit?: Prisma.MisskonTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonTagInclude<ExtArgs> | null
  /**
   * The data needed to create a MisskonTag.
   */
  data: Prisma.XOR<Prisma.MisskonTagCreateInput, Prisma.MisskonTagUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * MisskonTag createMany
 */
export type MisskonTagCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MisskonTags.
   */
  data: Prisma.MisskonTagCreateManyInput | Prisma.MisskonTagCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MisskonTag createManyAndReturn
 */
export type MisskonTagCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonTag
   */
  select?: Prisma.MisskonTagSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MisskonTag
   */
  omit?: Prisma.MisskonTagOmit<ExtArgs> | null
  /**
   * The data used to create many MisskonTags.
   */
  data: Prisma.MisskonTagCreateManyInput | Prisma.MisskonTagCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MisskonTag update
 */
export type MisskonTagUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonTag
   */
  select?: Prisma.MisskonTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MisskonTag
   */
  omit?: Prisma.MisskonTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonTagInclude<ExtArgs> | null
  /**
   * The data needed to update a MisskonTag.
   */
  data: Prisma.XOR<Prisma.MisskonTagUpdateInput, Prisma.MisskonTagUncheckedUpdateInput>
  /**
   * Choose, which MisskonTag to update.
   */
  where: Prisma.MisskonTagWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * MisskonTag updateMany
 */
export type MisskonTagUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MisskonTags.
   */
  data: Prisma.XOR<Prisma.MisskonTagUpdateManyMutationInput, Prisma.MisskonTagUncheckedUpdateManyInput>
  /**
   * Filter which MisskonTags to update
   */
  where?: Prisma.MisskonTagWhereInput
  /**
   * Limit how many MisskonTags to update.
   */
  limit?: number
}

/**
 * MisskonTag updateManyAndReturn
 */
export type MisskonTagUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonTag
   */
  select?: Prisma.MisskonTagSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MisskonTag
   */
  omit?: Prisma.MisskonTagOmit<ExtArgs> | null
  /**
   * The data used to update MisskonTags.
   */
  data: Prisma.XOR<Prisma.MisskonTagUpdateManyMutationInput, Prisma.MisskonTagUncheckedUpdateManyInput>
  /**
   * Filter which MisskonTags to update
   */
  where?: Prisma.MisskonTagWhereInput
  /**
   * Limit how many MisskonTags to update.
   */
  limit?: number
}

/**
 * MisskonTag upsert
 */
export type MisskonTagUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonTag
   */
  select?: Prisma.MisskonTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MisskonTag
   */
  omit?: Prisma.MisskonTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonTagInclude<ExtArgs> | null
  /**
   * The filter to search for the MisskonTag to update in case it exists.
   */
  where: Prisma.MisskonTagWhereUniqueInput
  /**
   * In case the MisskonTag found by the `where` argument doesn't exist, create a new MisskonTag with this data.
   */
  create: Prisma.XOR<Prisma.MisskonTagCreateInput, Prisma.MisskonTagUncheckedCreateInput>
  /**
   * In case the MisskonTag was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MisskonTagUpdateInput, Prisma.MisskonTagUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * MisskonTag delete
 */
export type MisskonTagDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonTag
   */
  select?: Prisma.MisskonTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MisskonTag
   */
  omit?: Prisma.MisskonTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonTagInclude<ExtArgs> | null
  /**
   * Filter which MisskonTag to delete.
   */
  where: Prisma.MisskonTagWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * MisskonTag deleteMany
 */
export type MisskonTagDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MisskonTags to delete
   */
  where?: Prisma.MisskonTagWhereInput
  /**
   * Limit how many MisskonTags to delete.
   */
  limit?: number
}

/**
 * MisskonTag.resources
 */
export type MisskonTag$resourcesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Misskon
   */
  select?: Prisma.MisskonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Misskon
   */
  omit?: Prisma.MisskonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonInclude<ExtArgs> | null
  where?: Prisma.MisskonWhereInput
  orderBy?: Prisma.MisskonOrderByWithRelationInput | Prisma.MisskonOrderByWithRelationInput[]
  cursor?: Prisma.MisskonWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MisskonScalarFieldEnum | Prisma.MisskonScalarFieldEnum[]
}

/**
 * MisskonTag without action
 */
export type MisskonTagDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonTag
   */
  select?: Prisma.MisskonTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MisskonTag
   */
  omit?: Prisma.MisskonTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonTagInclude<ExtArgs> | null
}
