
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Misskon` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Misskon
 * 
 */
export type MisskonModel = runtime.Types.Result.DefaultSelection<Prisma.$MisskonPayload>

export type AggregateMisskon = {
  _count: MisskonCountAggregateOutputType | null
  _avg: MisskonAvgAggregateOutputType | null
  _sum: MisskonSumAggregateOutputType | null
  _min: MisskonMinAggregateOutputType | null
  _max: MisskonMaxAggregateOutputType | null
}

export type MisskonAvgAggregateOutputType = {
  id: number | null
  status: number | null
}

export type MisskonSumAggregateOutputType = {
  id: number | null
  status: number | null
}

export type MisskonMinAggregateOutputType = {
  id: number | null
  key: string | null
  name: string | null
  url: string | null
  link: string | null
  status: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MisskonMaxAggregateOutputType = {
  id: number | null
  key: string | null
  name: string | null
  url: string | null
  link: string | null
  status: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MisskonCountAggregateOutputType = {
  id: number
  key: number
  name: number
  url: number
  link: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MisskonAvgAggregateInputType = {
  id?: true
  status?: true
}

export type MisskonSumAggregateInputType = {
  id?: true
  status?: true
}

export type MisskonMinAggregateInputType = {
  id?: true
  key?: true
  name?: true
  url?: true
  link?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type MisskonMaxAggregateInputType = {
  id?: true
  key?: true
  name?: true
  url?: true
  link?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type MisskonCountAggregateInputType = {
  id?: true
  key?: true
  name?: true
  url?: true
  link?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MisskonAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Misskon to aggregate.
   */
  where?: Prisma.MisskonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Misskons to fetch.
   */
  orderBy?: Prisma.MisskonOrderByWithRelationInput | Prisma.MisskonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MisskonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Misskons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Misskons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Misskons
  **/
  _count?: true | MisskonCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MisskonAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MisskonSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MisskonMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MisskonMaxAggregateInputType
}

export type GetMisskonAggregateType<T extends MisskonAggregateArgs> = {
      [P in keyof T & keyof AggregateMisskon]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMisskon[P]>
    : Prisma.GetScalarType<T[P], AggregateMisskon[P]>
}




export type MisskonGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MisskonWhereInput
  orderBy?: Prisma.MisskonOrderByWithAggregationInput | Prisma.MisskonOrderByWithAggregationInput[]
  by: Prisma.MisskonScalarFieldEnum[] | Prisma.MisskonScalarFieldEnum
  having?: Prisma.MisskonScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MisskonCountAggregateInputType | true
  _avg?: MisskonAvgAggregateInputType
  _sum?: MisskonSumAggregateInputType
  _min?: MisskonMinAggregateInputType
  _max?: MisskonMaxAggregateInputType
}

export type MisskonGroupByOutputType = {
  id: number
  key: string
  name: string
  url: string
  link: string
  status: number
  createdAt: Date
  updatedAt: Date
  _count: MisskonCountAggregateOutputType | null
  _avg: MisskonAvgAggregateOutputType | null
  _sum: MisskonSumAggregateOutputType | null
  _min: MisskonMinAggregateOutputType | null
  _max: MisskonMaxAggregateOutputType | null
}

export type GetMisskonGroupByPayload<T extends MisskonGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MisskonGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MisskonGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MisskonGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MisskonGroupByOutputType[P]>
      }
    >
  >



export type MisskonWhereInput = {
  AND?: Prisma.MisskonWhereInput | Prisma.MisskonWhereInput[]
  OR?: Prisma.MisskonWhereInput[]
  NOT?: Prisma.MisskonWhereInput | Prisma.MisskonWhereInput[]
  id?: Prisma.IntFilter<"Misskon"> | number
  key?: Prisma.StringFilter<"Misskon"> | string
  name?: Prisma.StringFilter<"Misskon"> | string
  url?: Prisma.StringFilter<"Misskon"> | string
  link?: Prisma.StringFilter<"Misskon"> | string
  status?: Prisma.IntFilter<"Misskon"> | number
  createdAt?: Prisma.DateTimeFilter<"Misskon"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Misskon"> | Date | string
  tags?: Prisma.MisskonTagListRelationFilter
}

export type MisskonOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  link?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  tags?: Prisma.MisskonTagOrderByRelationAggregateInput
}

export type MisskonWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  key?: string
  url?: string
  AND?: Prisma.MisskonWhereInput | Prisma.MisskonWhereInput[]
  OR?: Prisma.MisskonWhereInput[]
  NOT?: Prisma.MisskonWhereInput | Prisma.MisskonWhereInput[]
  name?: Prisma.StringFilter<"Misskon"> | string
  link?: Prisma.StringFilter<"Misskon"> | string
  status?: Prisma.IntFilter<"Misskon"> | number
  createdAt?: Prisma.DateTimeFilter<"Misskon"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Misskon"> | Date | string
  tags?: Prisma.MisskonTagListRelationFilter
}, "id" | "key" | "url">

export type MisskonOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  link?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MisskonCountOrderByAggregateInput
  _avg?: Prisma.MisskonAvgOrderByAggregateInput
  _max?: Prisma.MisskonMaxOrderByAggregateInput
  _min?: Prisma.MisskonMinOrderByAggregateInput
  _sum?: Prisma.MisskonSumOrderByAggregateInput
}

export type MisskonScalarWhereWithAggregatesInput = {
  AND?: Prisma.MisskonScalarWhereWithAggregatesInput | Prisma.MisskonScalarWhereWithAggregatesInput[]
  OR?: Prisma.MisskonScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MisskonScalarWhereWithAggregatesInput | Prisma.MisskonScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Misskon"> | number
  key?: Prisma.StringWithAggregatesFilter<"Misskon"> | string
  name?: Prisma.StringWithAggregatesFilter<"Misskon"> | string
  url?: Prisma.StringWithAggregatesFilter<"Misskon"> | string
  link?: Prisma.StringWithAggregatesFilter<"Misskon"> | string
  status?: Prisma.IntWithAggregatesFilter<"Misskon"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Misskon"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Misskon"> | Date | string
}

export type MisskonCreateInput = {
  key: string
  name: string
  url: string
  link: string
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  tags?: Prisma.MisskonTagCreateNestedManyWithoutResourcesInput
}

export type MisskonUncheckedCreateInput = {
  id?: number
  key: string
  name: string
  url: string
  link: string
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  tags?: Prisma.MisskonTagUncheckedCreateNestedManyWithoutResourcesInput
}

export type MisskonUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tags?: Prisma.MisskonTagUpdateManyWithoutResourcesNestedInput
}

export type MisskonUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tags?: Prisma.MisskonTagUncheckedUpdateManyWithoutResourcesNestedInput
}

export type MisskonCreateManyInput = {
  id?: number
  key: string
  name: string
  url: string
  link: string
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MisskonUpdateManyMutationInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MisskonUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MisskonCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  link?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MisskonAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type MisskonMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  link?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MisskonMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  link?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MisskonSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type MisskonListRelationFilter = {
  every?: Prisma.MisskonWhereInput
  some?: Prisma.MisskonWhereInput
  none?: Prisma.MisskonWhereInput
}

export type MisskonOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type MisskonCreateNestedManyWithoutTagsInput = {
  create?: Prisma.XOR<Prisma.MisskonCreateWithoutTagsInput, Prisma.MisskonUncheckedCreateWithoutTagsInput> | Prisma.MisskonCreateWithoutTagsInput[] | Prisma.MisskonUncheckedCreateWithoutTagsInput[]
  connectOrCreate?: Prisma.MisskonCreateOrConnectWithoutTagsInput | Prisma.MisskonCreateOrConnectWithoutTagsInput[]
  connect?: Prisma.MisskonWhereUniqueInput | Prisma.MisskonWhereUniqueInput[]
}

export type MisskonUncheckedCreateNestedManyWithoutTagsInput = {
  create?: Prisma.XOR<Prisma.MisskonCreateWithoutTagsInput, Prisma.MisskonUncheckedCreateWithoutTagsInput> | Prisma.MisskonCreateWithoutTagsInput[] | Prisma.MisskonUncheckedCreateWithoutTagsInput[]
  connectOrCreate?: Prisma.MisskonCreateOrConnectWithoutTagsInput | Prisma.MisskonCreateOrConnectWithoutTagsInput[]
  connect?: Prisma.MisskonWhereUniqueInput | Prisma.MisskonWhereUniqueInput[]
}

export type MisskonUpdateManyWithoutTagsNestedInput = {
  create?: Prisma.XOR<Prisma.MisskonCreateWithoutTagsInput, Prisma.MisskonUncheckedCreateWithoutTagsInput> | Prisma.MisskonCreateWithoutTagsInput[] | Prisma.MisskonUncheckedCreateWithoutTagsInput[]
  connectOrCreate?: Prisma.MisskonCreateOrConnectWithoutTagsInput | Prisma.MisskonCreateOrConnectWithoutTagsInput[]
  upsert?: Prisma.MisskonUpsertWithWhereUniqueWithoutTagsInput | Prisma.MisskonUpsertWithWhereUniqueWithoutTagsInput[]
  set?: Prisma.MisskonWhereUniqueInput | Prisma.MisskonWhereUniqueInput[]
  disconnect?: Prisma.MisskonWhereUniqueInput | Prisma.MisskonWhereUniqueInput[]
  delete?: Prisma.MisskonWhereUniqueInput | Prisma.MisskonWhereUniqueInput[]
  connect?: Prisma.MisskonWhereUniqueInput | Prisma.MisskonWhereUniqueInput[]
  update?: Prisma.MisskonUpdateWithWhereUniqueWithoutTagsInput | Prisma.MisskonUpdateWithWhereUniqueWithoutTagsInput[]
  updateMany?: Prisma.MisskonUpdateManyWithWhereWithoutTagsInput | Prisma.MisskonUpdateManyWithWhereWithoutTagsInput[]
  deleteMany?: Prisma.MisskonScalarWhereInput | Prisma.MisskonScalarWhereInput[]
}

export type MisskonUncheckedUpdateManyWithoutTagsNestedInput = {
  create?: Prisma.XOR<Prisma.MisskonCreateWithoutTagsInput, Prisma.MisskonUncheckedCreateWithoutTagsInput> | Prisma.MisskonCreateWithoutTagsInput[] | Prisma.MisskonUncheckedCreateWithoutTagsInput[]
  connectOrCreate?: Prisma.MisskonCreateOrConnectWithoutTagsInput | Prisma.MisskonCreateOrConnectWithoutTagsInput[]
  upsert?: Prisma.MisskonUpsertWithWhereUniqueWithoutTagsInput | Prisma.MisskonUpsertWithWhereUniqueWithoutTagsInput[]
  set?: Prisma.MisskonWhereUniqueInput | Prisma.MisskonWhereUniqueInput[]
  disconnect?: Prisma.MisskonWhereUniqueInput | Prisma.MisskonWhereUniqueInput[]
  delete?: Prisma.MisskonWhereUniqueInput | Prisma.MisskonWhereUniqueInput[]
  connect?: Prisma.MisskonWhereUniqueInput | Prisma.MisskonWhereUniqueInput[]
  update?: Prisma.MisskonUpdateWithWhereUniqueWithoutTagsInput | Prisma.MisskonUpdateWithWhereUniqueWithoutTagsInput[]
  updateMany?: Prisma.MisskonUpdateManyWithWhereWithoutTagsInput | Prisma.MisskonUpdateManyWithWhereWithoutTagsInput[]
  deleteMany?: Prisma.MisskonScalarWhereInput | Prisma.MisskonScalarWhereInput[]
}

export type MisskonCreateWithoutTagsInput = {
  key: string
  name: string
  url: string
  link: string
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MisskonUncheckedCreateWithoutTagsInput = {
  id?: number
  key: string
  name: string
  url: string
  link: string
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MisskonCreateOrConnectWithoutTagsInput = {
  where: Prisma.MisskonWhereUniqueInput
  create: Prisma.XOR<Prisma.MisskonCreateWithoutTagsInput, Prisma.MisskonUncheckedCreateWithoutTagsInput>
}

export type MisskonUpsertWithWhereUniqueWithoutTagsInput = {
  where: Prisma.MisskonWhereUniqueInput
  update: Prisma.XOR<Prisma.MisskonUpdateWithoutTagsInput, Prisma.MisskonUncheckedUpdateWithoutTagsInput>
  create: Prisma.XOR<Prisma.MisskonCreateWithoutTagsInput, Prisma.MisskonUncheckedCreateWithoutTagsInput>
}

export type MisskonUpdateWithWhereUniqueWithoutTagsInput = {
  where: Prisma.MisskonWhereUniqueInput
  data: Prisma.XOR<Prisma.MisskonUpdateWithoutTagsInput, Prisma.MisskonUncheckedUpdateWithoutTagsInput>
}

export type MisskonUpdateManyWithWhereWithoutTagsInput = {
  where: Prisma.MisskonScalarWhereInput
  data: Prisma.XOR<Prisma.MisskonUpdateManyMutationInput, Prisma.MisskonUncheckedUpdateManyWithoutTagsInput>
}

export type MisskonScalarWhereInput = {
  AND?: Prisma.MisskonScalarWhereInput | Prisma.MisskonScalarWhereInput[]
  OR?: Prisma.MisskonScalarWhereInput[]
  NOT?: Prisma.MisskonScalarWhereInput | Prisma.MisskonScalarWhereInput[]
  id?: Prisma.IntFilter<"Misskon"> | number
  key?: Prisma.StringFilter<"Misskon"> | string
  name?: Prisma.StringFilter<"Misskon"> | string
  url?: Prisma.StringFilter<"Misskon"> | string
  link?: Prisma.StringFilter<"Misskon"> | string
  status?: Prisma.IntFilter<"Misskon"> | number
  createdAt?: Prisma.DateTimeFilter<"Misskon"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Misskon"> | Date | string
}

export type MisskonUpdateWithoutTagsInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MisskonUncheckedUpdateWithoutTagsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MisskonUncheckedUpdateManyWithoutTagsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type MisskonCountOutputType
 */

export type MisskonCountOutputType = {
  tags: number
}

export type MisskonCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tags?: boolean | MisskonCountOutputTypeCountTagsArgs
}

/**
 * MisskonCountOutputType without action
 */
export type MisskonCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonCountOutputType
   */
  select?: Prisma.MisskonCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MisskonCountOutputType without action
 */
export type MisskonCountOutputTypeCountTagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MisskonTagWhereInput
}


export type MisskonSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  name?: boolean
  url?: boolean
  link?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tags?: boolean | Prisma.Misskon$tagsArgs<ExtArgs>
  _count?: boolean | Prisma.MisskonCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["misskon"]>

export type MisskonSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  name?: boolean
  url?: boolean
  link?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["misskon"]>

export type MisskonSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  name?: boolean
  url?: boolean
  link?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["misskon"]>

export type MisskonSelectScalar = {
  id?: boolean
  key?: boolean
  name?: boolean
  url?: boolean
  link?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MisskonOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "key" | "name" | "url" | "link" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["misskon"]>
export type MisskonInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tags?: boolean | Prisma.Misskon$tagsArgs<ExtArgs>
  _count?: boolean | Prisma.MisskonCountOutputTypeDefaultArgs<ExtArgs>
}
export type MisskonIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type MisskonIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $MisskonPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Misskon"
  objects: {
    tags: Prisma.$MisskonTagPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    key: string
    name: string
    url: string
    link: string
    status: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["misskon"]>
  composites: {}
}

export type MisskonGetPayload<S extends boolean | null | undefined | MisskonDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MisskonPayload, S>

export type MisskonCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MisskonFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: MisskonCountAggregateInputType | true
  }

export interface MisskonDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Misskon'], meta: { name: 'Misskon' } }
  /**
   * Find zero or one Misskon that matches the filter.
   * @param {MisskonFindUniqueArgs} args - Arguments to find a Misskon
   * @example
   * // Get one Misskon
   * const misskon = await prisma.misskon.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MisskonFindUniqueArgs>(args: Prisma.SelectSubset<T, MisskonFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MisskonClient<runtime.Types.Result.GetResult<Prisma.$MisskonPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Misskon that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MisskonFindUniqueOrThrowArgs} args - Arguments to find a Misskon
   * @example
   * // Get one Misskon
   * const misskon = await prisma.misskon.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MisskonFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MisskonFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MisskonClient<runtime.Types.Result.GetResult<Prisma.$MisskonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Misskon that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MisskonFindFirstArgs} args - Arguments to find a Misskon
   * @example
   * // Get one Misskon
   * const misskon = await prisma.misskon.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MisskonFindFirstArgs>(args?: Prisma.SelectSubset<T, MisskonFindFirstArgs<ExtArgs>>): Prisma.Prisma__MisskonClient<runtime.Types.Result.GetResult<Prisma.$MisskonPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Misskon that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MisskonFindFirstOrThrowArgs} args - Arguments to find a Misskon
   * @example
   * // Get one Misskon
   * const misskon = await prisma.misskon.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MisskonFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MisskonFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MisskonClient<runtime.Types.Result.GetResult<Prisma.$MisskonPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Misskons that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MisskonFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Misskons
   * const misskons = await prisma.misskon.findMany()
   * 
   * // Get first 10 Misskons
   * const misskons = await prisma.misskon.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const misskonWithIdOnly = await prisma.misskon.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MisskonFindManyArgs>(args?: Prisma.SelectSubset<T, MisskonFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MisskonPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Misskon.
   * @param {MisskonCreateArgs} args - Arguments to create a Misskon.
   * @example
   * // Create one Misskon
   * const Misskon = await prisma.misskon.create({
   *   data: {
   *     // ... data to create a Misskon
   *   }
   * })
   * 
   */
  create<T extends MisskonCreateArgs>(args: Prisma.SelectSubset<T, MisskonCreateArgs<ExtArgs>>): Prisma.Prisma__MisskonClient<runtime.Types.Result.GetResult<Prisma.$MisskonPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Misskons.
   * @param {MisskonCreateManyArgs} args - Arguments to create many Misskons.
   * @example
   * // Create many Misskons
   * const misskon = await prisma.misskon.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MisskonCreateManyArgs>(args?: Prisma.SelectSubset<T, MisskonCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Misskons and returns the data saved in the database.
   * @param {MisskonCreateManyAndReturnArgs} args - Arguments to create many Misskons.
   * @example
   * // Create many Misskons
   * const misskon = await prisma.misskon.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Misskons and only return the `id`
   * const misskonWithIdOnly = await prisma.misskon.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MisskonCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MisskonCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MisskonPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Misskon.
   * @param {MisskonDeleteArgs} args - Arguments to delete one Misskon.
   * @example
   * // Delete one Misskon
   * const Misskon = await prisma.misskon.delete({
   *   where: {
   *     // ... filter to delete one Misskon
   *   }
   * })
   * 
   */
  delete<T extends MisskonDeleteArgs>(args: Prisma.SelectSubset<T, MisskonDeleteArgs<ExtArgs>>): Prisma.Prisma__MisskonClient<runtime.Types.Result.GetResult<Prisma.$MisskonPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Misskon.
   * @param {MisskonUpdateArgs} args - Arguments to update one Misskon.
   * @example
   * // Update one Misskon
   * const misskon = await prisma.misskon.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MisskonUpdateArgs>(args: Prisma.SelectSubset<T, MisskonUpdateArgs<ExtArgs>>): Prisma.Prisma__MisskonClient<runtime.Types.Result.GetResult<Prisma.$MisskonPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Misskons.
   * @param {MisskonDeleteManyArgs} args - Arguments to filter Misskons to delete.
   * @example
   * // Delete a few Misskons
   * const { count } = await prisma.misskon.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MisskonDeleteManyArgs>(args?: Prisma.SelectSubset<T, MisskonDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Misskons.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MisskonUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Misskons
   * const misskon = await prisma.misskon.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MisskonUpdateManyArgs>(args: Prisma.SelectSubset<T, MisskonUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Misskons and returns the data updated in the database.
   * @param {MisskonUpdateManyAndReturnArgs} args - Arguments to update many Misskons.
   * @example
   * // Update many Misskons
   * const misskon = await prisma.misskon.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Misskons and only return the `id`
   * const misskonWithIdOnly = await prisma.misskon.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MisskonUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MisskonUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MisskonPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Misskon.
   * @param {MisskonUpsertArgs} args - Arguments to update or create a Misskon.
   * @example
   * // Update or create a Misskon
   * const misskon = await prisma.misskon.upsert({
   *   create: {
   *     // ... data to create a Misskon
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Misskon we want to update
   *   }
   * })
   */
  upsert<T extends MisskonUpsertArgs>(args: Prisma.SelectSubset<T, MisskonUpsertArgs<ExtArgs>>): Prisma.Prisma__MisskonClient<runtime.Types.Result.GetResult<Prisma.$MisskonPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Misskons.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MisskonCountArgs} args - Arguments to filter Misskons to count.
   * @example
   * // Count the number of Misskons
   * const count = await prisma.misskon.count({
   *   where: {
   *     // ... the filter for the Misskons we want to count
   *   }
   * })
  **/
  count<T extends MisskonCountArgs>(
    args?: Prisma.Subset<T, MisskonCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MisskonCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Misskon.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MisskonAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MisskonAggregateArgs>(args: Prisma.Subset<T, MisskonAggregateArgs>): Prisma.PrismaPromise<GetMisskonAggregateType<T>>

  /**
   * Group by Misskon.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MisskonGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MisskonGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MisskonGroupByArgs['orderBy'] }
      : { orderBy?: MisskonGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MisskonGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMisskonGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Misskon model
 */
readonly fields: MisskonFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Misskon.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MisskonClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tags<T extends Prisma.Misskon$tagsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Misskon$tagsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MisskonTagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Misskon model
 */
export interface MisskonFieldRefs {
  readonly id: Prisma.FieldRef<"Misskon", 'Int'>
  readonly key: Prisma.FieldRef<"Misskon", 'String'>
  readonly name: Prisma.FieldRef<"Misskon", 'String'>
  readonly url: Prisma.FieldRef<"Misskon", 'String'>
  readonly link: Prisma.FieldRef<"Misskon", 'String'>
  readonly status: Prisma.FieldRef<"Misskon", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Misskon", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Misskon", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Misskon findUnique
 */
export type MisskonFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Misskon
   */
  select?: Prisma.MisskonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Misskon
   */
  omit?: Prisma.MisskonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonInclude<ExtArgs> | null
  /**
   * Filter, which Misskon to fetch.
   */
  where: Prisma.MisskonWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Misskon findUniqueOrThrow
 */
export type MisskonFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Misskon
   */
  select?: Prisma.MisskonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Misskon
   */
  omit?: Prisma.MisskonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonInclude<ExtArgs> | null
  /**
   * Filter, which Misskon to fetch.
   */
  where: Prisma.MisskonWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Misskon findFirst
 */
export type MisskonFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Misskon
   */
  select?: Prisma.MisskonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Misskon
   */
  omit?: Prisma.MisskonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonInclude<ExtArgs> | null
  /**
   * Filter, which Misskon to fetch.
   */
  where?: Prisma.MisskonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Misskons to fetch.
   */
  orderBy?: Prisma.MisskonOrderByWithRelationInput | Prisma.MisskonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Misskons.
   */
  cursor?: Prisma.MisskonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Misskons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Misskons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Misskons.
   */
  distinct?: Prisma.MisskonScalarFieldEnum | Prisma.MisskonScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Misskon findFirstOrThrow
 */
export type MisskonFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Misskon
   */
  select?: Prisma.MisskonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Misskon
   */
  omit?: Prisma.MisskonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonInclude<ExtArgs> | null
  /**
   * Filter, which Misskon to fetch.
   */
  where?: Prisma.MisskonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Misskons to fetch.
   */
  orderBy?: Prisma.MisskonOrderByWithRelationInput | Prisma.MisskonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Misskons.
   */
  cursor?: Prisma.MisskonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Misskons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Misskons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Misskons.
   */
  distinct?: Prisma.MisskonScalarFieldEnum | Prisma.MisskonScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Misskon findMany
 */
export type MisskonFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Misskon
   */
  select?: Prisma.MisskonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Misskon
   */
  omit?: Prisma.MisskonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonInclude<ExtArgs> | null
  /**
   * Filter, which Misskons to fetch.
   */
  where?: Prisma.MisskonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Misskons to fetch.
   */
  orderBy?: Prisma.MisskonOrderByWithRelationInput | Prisma.MisskonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Misskons.
   */
  cursor?: Prisma.MisskonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Misskons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Misskons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Misskons.
   */
  distinct?: Prisma.MisskonScalarFieldEnum | Prisma.MisskonScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Misskon create
 */
export type MisskonCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Misskon
   */
  select?: Prisma.MisskonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Misskon
   */
  omit?: Prisma.MisskonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonInclude<ExtArgs> | null
  /**
   * The data needed to create a Misskon.
   */
  data: Prisma.XOR<Prisma.MisskonCreateInput, Prisma.MisskonUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Misskon createMany
 */
export type MisskonCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Misskons.
   */
  data: Prisma.MisskonCreateManyInput | Prisma.MisskonCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Misskon createManyAndReturn
 */
export type MisskonCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Misskon
   */
  select?: Prisma.MisskonSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Misskon
   */
  omit?: Prisma.MisskonOmit<ExtArgs> | null
  /**
   * The data used to create many Misskons.
   */
  data: Prisma.MisskonCreateManyInput | Prisma.MisskonCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Misskon update
 */
export type MisskonUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Misskon
   */
  select?: Prisma.MisskonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Misskon
   */
  omit?: Prisma.MisskonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonInclude<ExtArgs> | null
  /**
   * The data needed to update a Misskon.
   */
  data: Prisma.XOR<Prisma.MisskonUpdateInput, Prisma.MisskonUncheckedUpdateInput>
  /**
   * Choose, which Misskon to update.
   */
  where: Prisma.MisskonWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Misskon updateMany
 */
export type MisskonUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Misskons.
   */
  data: Prisma.XOR<Prisma.MisskonUpdateManyMutationInput, Prisma.MisskonUncheckedUpdateManyInput>
  /**
   * Filter which Misskons to update
   */
  where?: Prisma.MisskonWhereInput
  /**
   * Limit how many Misskons to update.
   */
  limit?: number
}

/**
 * Misskon updateManyAndReturn
 */
export type MisskonUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Misskon
   */
  select?: Prisma.MisskonSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Misskon
   */
  omit?: Prisma.MisskonOmit<ExtArgs> | null
  /**
   * The data used to update Misskons.
   */
  data: Prisma.XOR<Prisma.MisskonUpdateManyMutationInput, Prisma.MisskonUncheckedUpdateManyInput>
  /**
   * Filter which Misskons to update
   */
  where?: Prisma.MisskonWhereInput
  /**
   * Limit how many Misskons to update.
   */
  limit?: number
}

/**
 * Misskon upsert
 */
export type MisskonUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Misskon
   */
  select?: Prisma.MisskonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Misskon
   */
  omit?: Prisma.MisskonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonInclude<ExtArgs> | null
  /**
   * The filter to search for the Misskon to update in case it exists.
   */
  where: Prisma.MisskonWhereUniqueInput
  /**
   * In case the Misskon found by the `where` argument doesn't exist, create a new Misskon with this data.
   */
  create: Prisma.XOR<Prisma.MisskonCreateInput, Prisma.MisskonUncheckedCreateInput>
  /**
   * In case the Misskon was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MisskonUpdateInput, Prisma.MisskonUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Misskon delete
 */
export type MisskonDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Misskon
   */
  select?: Prisma.MisskonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Misskon
   */
  omit?: Prisma.MisskonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonInclude<ExtArgs> | null
  /**
   * Filter which Misskon to delete.
   */
  where: Prisma.MisskonWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Misskon deleteMany
 */
export type MisskonDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Misskons to delete
   */
  where?: Prisma.MisskonWhereInput
  /**
   * Limit how many Misskons to delete.
   */
  limit?: number
}

/**
 * Misskon.tags
 */
export type Misskon$tagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MisskonTag
   */
  select?: Prisma.MisskonTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MisskonTag
   */
  omit?: Prisma.MisskonTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonTagInclude<ExtArgs> | null
  where?: Prisma.MisskonTagWhereInput
  orderBy?: Prisma.MisskonTagOrderByWithRelationInput | Prisma.MisskonTagOrderByWithRelationInput[]
  cursor?: Prisma.MisskonTagWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MisskonTagScalarFieldEnum | Prisma.MisskonTagScalarFieldEnum[]
}

/**
 * Misskon without action
 */
export type MisskonDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Misskon
   */
  select?: Prisma.MisskonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Misskon
   */
  omit?: Prisma.MisskonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MisskonInclude<ExtArgs> | null
}
