import { ResourceStatus } from '@shared'
import { db, newCommand } from 'src/utils'

const keys = [
    'IMISS',
    'XIUREN',
    'XiaoYu',
    '[AI Generated]',
    'XingYan',
    'MiStar',
    '[Ugirls爱尤物]',
    'YouMi',
    'HuaYang',
    '[KING8舞團]',
    '[Private Photoshoot]',
    'Coser@蠢沫沫',
    'Coser@Byoru',
    'Coser@布丁大法',
    'Coser@小仓千代w',
    'Coser@白银81',
    'Coser@蜜汁猫裘',
    'Coser@云溪溪',
    'Coser@Ely_eee',
    'Coser@NAGISA魔物喵',
    'Coser@雪晴Astra',
    'Coser@奈汐酱nice',
    '可可西yyy',
    'Coser@阿薰kaOri',
    'Coser@Bangni邦尼',
    'Coser@PuyPuy',
    'Coser@Messie Huang',
    '[精选街拍作品]',
    '[模密運動甜心]',
    'Coser@二佐Nisa',
    'Coser@隼隼子',
    'Coser@桜井宁宁',
    'Coser@ZinieQ',
    'Coser@Candy_Ball',
    'Coser@Pyon',
    'Coser@PoppaChan',
    'Coser@幼愛Youmeko',
    'Yeon Woo (연우)',
    'Coser@喜欢爱理吗',
    'Coser@Imyuiichann',
    'Coser@源纱希喵喵喵',
    'Coser@花柒Hana',
    'Coser@黏黏团子兔',
    'Coser@yuuhui玉汇',
    'Coser@疯猫ss',
    'Coser@Rizuna',
    'Coser@山崎雷纳',
    'Coser@智惠姐姐',
    'Coser@UmekoJ',
    'Coser@瓜希酱',
    'Coser@封疆疆v',
    'Coser@星澜是澜澜叫澜妹呀',
    'Coser@香草喵露露',
    'Coser@过期米线线喵',
    'Coser@miko酱ww',
    'Coser@阿包也是兔娘',
    'Coser@发条少女 (迷之呆梨)',
    'Coser@屿鱼',
    'Coser@AT鲨',
    'Coser@清水由乃',
    'Coser@九柒喵',
    'Coser@您的蛋蛋',
    'Coser@Quan冉有点饿',
    'Coser@rioko凉凉子',
    'Coser@Tiny Asa',
    'Coser@洛桑w伊梓',
    'Coser@矢量鱼',
    'Coser@Sayo Momo',
    'Coser@蜜桃少女是依酱呀',
    'Coser@少女映画',
    'Coser@小樱',
    'Coser@樱岛嗷一',
    'Coser@亚马逊鲶鱼',
    'Coser@纸悦Etsu_ko',
    'Coser@不可爱羚',
    'Coser@星黛鹿鹿',
    'Coser@Kikiwan (キキワン)',
    'Coser@Mui Anzai (安斎夢唯)',
    'Coser@Maou Mo',
    'Coser@ShiragaYanko',
    'Coser@Yeolmu',
    '西好运',
    'Coser@末夜787',
    'Coser@习呆呆',
    'Coser@Nyako喵子',
    'Coser@桜桃喵',
    'Coser@不呆猫',
    'Coser@是三不是世w',
    'Coser@Money冷冷',
    'Coser@鬼畜瑶在不在w',
    'Coser@Seele麦麦',
    'Coser@Kurumi (クルミ)',
    'Coser@Ashyliiii爱莉',
    'Coser@冬马路纱',
    'Yeolmu',
    'Coser@零崎沙耶',
    'Dongeuran (동그란)',
    'Coser@羽生三未',
    'Coser@Hana Bunny',
    'Coser@眼酱大魔王w',
    'Coser@日奈娇',
    'Coser@前野太太',
    'Coser@霜月shimo',
    'Coser@Sameki',
    'Coser@G44不会受伤',
    'Coser@Natsuko夏夏子',
    'Coser@七七娜娜子',
    'Coser@51酱',
    'Bomi (보미)',
    'Coser@千反田鹿子',
    'Coser@糖果果Candy',
    'Coser@neko酱',
    'Coser@阿雪雪',
    'Coser@如月灰',
    '文茜cool',
    'Coser@阿半今天很开心',
    'Coser@虎森森',
    'Coser@九言',
    'Coser@神楽坂真冬',
    'Coser@仙女月',
    'Coser@无颜小天使wy',
    'Coser@艾西aiwest',
    'Coser@芦苇苇苇',
    'Coser@流年不停_w',
    'Coser@雯妹不讲道理',
    'Coser@面饼仙儿',
    '[森萝财团写真]',
    'Coser@轩萧学姐',
    'Coser@女主K',
    'Coser@小和甜酒',
    'Coser@水淼Aqua',
    'Coser@Tina很妖孽呀',
    'Coser@切切Celia',
    'Coser@Hachi_小芭',
    'Coser@masaki雅祈',
    'Coser@一只猫猫帽',
    'Coser@半半子',
    'Coser@浅安安',
    'Coser@一米八的大梨子',
    'Coser@安食Ajiki',
    'Coser@雪琪SAMA',
    'Coser@九曲Jean',
    'Coser@柒柒要乖哦',
    'Coser@五更百鬼',
    'Coser@双木扶苏',
    'Coser@Uriうり',
    'Coser@Ulichan',
    'Coser@胡桃猫Kurumineko',
    'Coser@兔胖胖',
    'Coser@Sally多啦雪',
    'Coser@いくみ (193iKkyu3)',
    'Coser@白栎Shirly',
    'Coser@伊喵君',
    'Coser@Mime (弥美)',
    'Coser@神沢永莉',
    'Coser@抖娘-利世',
    'Coser@けん研 (けんけん)',
    'Coser@一小央泽 (yixiaoyangze)',
    'Coser@KuukoW',
    'Coser@喵帕斯',
    '[她们印象]',
    'Coser@宮本桜',
    'Coser@一千只猫薄禾',
    'Coser@鹿八岁',
    'Coser@楊衣Yangyi',
    'Coser@起司块wii',
    'Coser@Xenon',
    'Coser@Peach milky',
    '[Limerence原创]',
    '曲奇软fufu',
    'Coser@小容仔咕咕咕w',
    'Coser@lunananya',
    'Coser@Hane Ame',
    '[SweatGirl]',
    'Coser@星之迟迟Hoshilily',
    'Coser@KANEKO_咔喵',
    '[小众视觉]',
    '小u优优子',
    '[MZSOCK爱美足]',
    '毛毛帽',
    'Coser@くろてぃあ (くろ)',
    'Coser@Momoko葵葵',
    'Coser@贝贝琪Becky',
    'Coser@皮皮奶可可爱了啦',
    'Coser@一色雨',
    'Coser@十万珍吱伏特',
    'Coser@Misaki Sai',
    'Coser@Angel Chan',
    'Coser@Maria Desu',
    'Coser@Zyra秋',
    'Coser@洛璃LoLiSAMA',
    'Coser@抱走莫子aa',
    'Coser@Anaimiya奶咪',
    'Coser@上杉绘梨落',
    'Coser@Choi Ji Yun',
    'Coser@桜满三时',
    'Coser@可可小白兔',
    'Coser@萌芽儿o0',
    'Coser@葛生w',
    'Coser@HaL(ハル)',
    'Coser@是夙卿呀',
    'Coser@刺青Poi',
    'Coser@贞子蜜桃',
    'Coser@冬马路纱',
    'Auddk_77 (명아)',
    'Aheyanlz(噗噗)',
    '[三禾摄影]',
    '[ROSI写真]',
    '小羊蛋卷',
    'Coser@cocopie0218',
    'Coser@三無人型',
    'Coser@三度_69',
    'Coser@Mikehouse (ミケ)',
    'Coser@清水凪',
    'Coser@九九八XY',
    'Coser@西园寺南歌',
    'Coser@Alina Becker',
    '[内购无水印]',
    'Coser@Miinmeow',
    'Coser@是一只熊仔吗',
    'Coser@麻花麻花酱',
    'Coser@Atsuki (あつき)',
    'Coser@幼水铃衣',
    'Coser@无影喵喵Ghost',
    'Coser@小空sora',
    'Coser@CatDemon喵崽',
    'Coser@樱落酱w',
    '[IESS异思趣向]',
    'Coser@Shika小鹿鹿',
    'Coser@麻薯好吃',
    '[AIGirl]',
    'Coser@香草奶喵',
    'Coser@花兮_honoka',
    'Coser@真宝',
    'Coser@芝心蛋奶烧',
    'Coser@猫大人',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
    // 'Coser@一千只猫薄禾',
]

export default newCommand('ignore', {
    description: '忽略资源',
    action,
})

async function action() {
    await db.misskon.updateMany({
        where: {
            OR: keys.map(item => ({
                name: {
                    startsWith: item,
                },
            })),
            status: ResourceStatus.Undownload,
        },
        data: {
            status: ResourceStatus.CanDownload,
        },
    })
    await db.$disconnect()
}
